#!/usr/bin/env python
# license removed for brevity
__author__ = 'fiorellasibona'
__author__ += ' & ant0ine'
import rospy
import math

import actionlib
from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
from actionlib_msgs.msg import GoalStatus
from geometry_msgs.msg import Pose, Point, Quaternion
from tf.transformations import quaternion_from_euler
from std_msgs.msg import Bool

try:
    from trader.msg import Task, actionToDo
    msgCheck = True
except:
    print("Trader Custom msg not available")
    msgCheck = False

class MoveBaseSeq():

    def __init__(self):

        rospy.init_node('move_base_sequence')
        points_seq = rospy.get_param('move_base_seq/p_seq', '[0,0,0]')
        # Only yaw angle required (no ratotions around x and y axes) in deg:
        yaweulerangles_seq = rospy.get_param('move_base_seq/yea_seq')


        #List of goal quaternions:
        quat_seq = list()
        #List of goal poses:
        self.pose_seq = list()
        self.goal_cnt = 0
        for yawangle in yaweulerangles_seq:
            #Unpacking the quaternion tuple and passing it as arguments to Quaternion message constructor
            quat_seq.append(Quaternion(*(quaternion_from_euler(0, 0, yawangle*math.pi/180, axes='sxyz'))))
        n = 3
        # Returns a list of lists [[point1], [point2],...[pointn]]
        points = [points_seq[i:i+n] for i in range(0, len(points_seq), n)]
        rospy.loginfo(str(points))
        for point in points:
            #Exploit n variable to cycle in quat_seq
            self.pose_seq.append(Pose(Point(*point),quat_seq[n-3]))
            n += 1
        #rospy.loginfo(str(self.pose_seq))

        # List of task to perform on the different goal
        # We make sure we have enough task to do in the list
        self.task_seq = [actionToDo() for k in range(len(self.pose_seq))]
        # For now the task do not do anything
        for task in self.task_seq:
            task.waitTime = 1 #sec


        # For timeout purpose with the last received msg
        self.last_msg = rospy.Time.now()
        self.timeFinishList = rospy.Time.now()
        # Subscriber to receive message
        self.sub = rospy.Subscriber("goalSender", Task, self.readNewGoal_cb)
        # I use a busy waiting to wait the server feddback
        self.goalReached = False
        # When all goals will be reached we will wait
        self.allGoalsReached = False

        # Create a publisher to let other nodes if the robot is idle or not
        self.isIdle_pub = rospy.Publisher("isIdle", Bool, 1)

        #Create action client
        self.client = actionlib.SimpleActionClient('move_base',MoveBaseAction)
        rospy.loginfo("Waiting for move_base action server...")
        wait = self.client.wait_for_server(rospy.Duration(5.0))
        if not wait:
            rospy.logerr("Action server not available!")
            rospy.signal_shutdown("Action server not available!")
            return
        rospy.loginfo("Connected to move base server")
        rospy.loginfo("Starting goals achievements ...")
        self.runNode()

    def readNewGoal_cb(self, msg):
        self.pose_seq.append(msg.goalPosition_p)
        self.task_seq.append(msg.toDo)
        self.last_msg = rospy.Time.now()
        self.allGoalsReached = False
        rospy.loginfo("We Got A NEW GOAL")

    def active_cb(self):
        rospy.loginfo("Goal pose "+str(self.goal_cnt+1)+\
                      " is now being processed by the Action Server...")

    def feedback_cb(self, feedback):
        #rospy.loginfo("Feedback for goal "+str(self.goal_cnt)+": "+str(feedback))
        rospy.loginfo("Feedback for goal pose "+str(self.goal_cnt+1)+" received")

    def done_cb(self, status, result):
        self.goalReached = True
        self.goal_cnt += 1

        # Reference for terminal status values: 
        # http://docs.ros.org/diamondback/api/actionlib_msgs/html/msg/GoalStatus.html
        if status == 2:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+\
                          " received a cancel request after it started executing, completed execution!")

        if status == 3:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" reached")

        if status == 4:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" was aborted by the Action Server")
            # rospy.signal_shutdown("Goal pose "+str(self.goal_cnt)+" aborted, shutting down!")
            return

        if status == 5:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+" has been rejected by the Action Server")
            # rospy.signal_shutdown("Goal pose "+str(self.goal_cnt)+" rejected, shutting down!")
            return

        if status == 8:
            rospy.loginfo("Goal pose "+str(self.goal_cnt)+\
                          " received a cancel request before it started executing, successfully cancelled!")

    def movebase_client(self, nextPose):
        """
        Send a goal to the SimpleAction Server
        """
        # Prepare Message
        goal = MoveBaseGoal()
        goal.target_pose.header.frame_id = "map"
        goal.target_pose.header.stamp = rospy.Time.now()
        goal.target_pose.pose = nextPose
        # Log
        rospy.loginfo("Sending goal pose "+str(self.goal_cnt+1)+" to Action Server")
        rospy.loginfo(str(self.pose_seq[self.goal_cnt]))
        # Send message
        self.client.send_goal(goal, self.done_cb, self.active_cb, self.feedback_cb)
        rospy.logerr("sent!")
        # rospy.spin()
        return

    def performTask(self, task):
        rospy.loginfo("Starting task at the last reached position")
        rospy.loginfo("Waiting " + str(task.waitTime) + " sec here")
        rospy.sleep(task.waitTime)
        return

    def runNode(self):
        rospy.loginfo("Starting while loop")
        while not rospy.is_shutdown():
            rospy.sleep(0.5)

            # We advertise if the robot is idle or not. We consider it
            # to be in an 'idle' state when all the tasks this node received
            # have been done/achieved by the nav stack
            state = Bool()
            state.data = self.allGoalsReached
            self.isIdle_pub.publish(state)

            if self.goal_cnt < len(self.pose_seq):
                # Sending a new goal to the stack
                rospy.logwarn("Sending new goal")
                self.goalReached = False
                self.movebase_client(self.pose_seq[self.goal_cnt])

                # Wait for callback of goal being reached
                while not self.goalReached:
                    rospy.sleep(0.5)
                    rospy.loginfo("Small wait")

                # Goal achieved, perform a task
                task = 0 # for now 
                self.performTask(self.task_seq[self.goal_cnt])
            else:
                # The list of nodes has been visited
                self.allGoalsReached = True
                self.timeFinishList = rospy.Time.now()

            # Auto closing after 5min
            timeoutDelay = 300 # sec
            if rospy.Time.now() - self.last_msg > rospy.Duration(timeoutDelay)\
                    and rospy.Time.now() - self.timeFinishList > rospy.Duration(timeoutDelay):
                rospy.logwarn("QUIT")
                rospy.signal_shutdown("Timeout, shutting down!")
                return


if __name__ == '__main__':
    try:
        if msgCheck:
            MoveBaseSeq()
    except rospy.ROSInterruptException:
        rospy.loginfo("Navigation finished.")
